format_version: 3
pipelines:
  deploy_to_cluster:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
      KUBE_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IlRXVDd6MmNFRWtNcFduTUg2cmJzcm5zZXVzNGIwVUUtdUNncDJpZzJpd0kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJnb2NkZG9uZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXh4cnhoIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwZDYzZGU4Ni04ZjE0LTQ2MGUtOGUzMi1iZThkYjM1MmVmYWMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z29jZGRvbmU6ZGVmYXVsdCJ9.h0kxvLP_OzItAVqgMlqTBtIF2Z4PCtrK_g01wj78Wz31uwcROrQCQRCvxRohbp6kqSn-4oo3_hYCUmHdZuwxnYVw2FcYpDwu-rjRoVqrjwtq869WMWis-V3qAxXHIlh4t8VcjTBfnkK6wWFmqLQU-mgh6ylETZn01qBqCsYhZpbqlkQ0LuGkUTbh3PUeIAMvRv3xeKzJXYSg0WdKGn2lEEDcCXc_KYQW-vnU9h06drrE5Eobo5ZYAZN46X0Qh3zE-CYeMXZNSWQQPlRjMzQPPf0b0Cw7yDWB2Lmt2OFN9TEXNWqIn0gnKG-M2Jcklr_iI8ScuplYkIXpVrPQ9yOMAw
    materials:
      upstream:
        pipeline: test_application
        stage: test_app_image
        name: upstream_pipeline
      SourceCodeRepo:
        git: https://github.com/gocd-demo/node-bulletin-board.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - deploy_to_cluster:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app1
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_publish_image/test_application
                stage: build_and_publish_image
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                command: ./app-deployment.sh
                run_if: passed
