format_version: 3
pipelines:
  qa-testrun-pipeline-new:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@bitbucket.org:centraltechnology/powerbuy-headless.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - qa-testrun-stage-new:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          qa-testrun-job-new:
            timeout: 0
            environment_variables:
              PWD: /go/pipelines/qatestnew-pipeline
              TESTDATA: 12345
            elastic_profile_id: demo-app1
            tasks:
            - exec:
                arguments:
                - -c
                - docker run --name qacont -v $PWD:/robot -i suresh528kumar/qatest:4
                  --name "pwb-test" --variable ENV:staging --variable DEVICE_PLATFORM:web
                  --include testrailid:C138480 --outputdir Report testcases/homepage/homepage.robot
                  && export TESTDATA=$(docker inspect --format="{{.Id}}" qacont) &&
                  echo The ContainerID is $TESTDATA && docker cp $TESTDATA:/robot/Report
                  /home/go/.ssh/devops
                command: /bin/bash
                run_if: passed
