format_version: 3
pipelines:
  qa-buildimg-pipeline:
    group: QA-TEST-GROUP
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      upstream:
        git: git@bitbucket.org:centraltechnology/robot-proxy.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - qa-buildimg-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          qa-buildimg-job:
            timeout: 0
            environment_variables:
              DOCKERHUB_USERNAME: suresh528kumar
            elastic_profile_id: demo-app1
            artifacts:
            - external:
                id: qaartifact
                store_id: dockerhub
                configuration:
                  options:
                    BuildFile: ''
                    Tag: ${GO_PIPELINE_LABEL}
                    Image: ${DOCKERHUB_USERNAME}/qatest
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/qatest:$GO_PIPELINE_LABEL .
                  -f Dockerfile
                command: /bin/bash
                run_if: passed
